# Generated by Django 5.1 on 2025-01-11 13:31

import FoldersFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=FoldersFiles.models.upload_to)),
                ('resource', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
