# Generated by Django 5.1 on 2024-09-03 07:50

import FoldersFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=FoldersFiles.models.upload_to),
        ),
    ]
