# Generated by Django 5.1 on 2024-09-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0004_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='FoldersFiles.folder'),
            preserve_default=False,
        ),
    ]
