# Generated by Django 5.1 on 2024-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0005_alter_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
