# Generated by Django 5.1 on 2024-09-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0006_file_file_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
    ]
