# Generated by Django 5.1 on 2024-09-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0007_alter_file_options_alter_folder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['id']},
        ),
    ]
