# Generated by Django 5.1 on 2024-09-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0008_alter_file_options_alter_folder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.CreateModel(
            name='FolderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('default', 'default'), ('full_access', 'Full Access'), ('part_access', 'Part Access'), ('no_access', 'No Access')], max_length=25)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoldersFiles.folder')),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
