# Generated by Django 5.1 on 2024-09-26 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0009_remove_file_owner_remove_folder_owner_folderrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderrole',
            name='role',
            field=models.CharField(choices=[('default', 'default'), ('full_access', 'Full Access'), ('part_access', 'Part Access'), ('no_access', 'No Access')], default=('no_access', 'No Access'), max_length=25),
        ),
        migrations.AlterField(
            model_name='folderrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
