# Generated by Django 5.1 on 2024-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0010_alter_folderrole_role_alter_folderrole_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.CharField(max_length=50),
        ),
    ]
