# Generated by Django 5.1 on 2024-11-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0011_alter_file_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderRole',
        ),
    ]
