# Generated by Django 5.1 on 2024-11-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0012_delete_folderrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder',
            new_name='resource',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
