# Generated by Django 5.1 on 2024-12-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoldersFiles', '0013_rename_folder_file_resource_delete_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
    ]
