# Generated by Django 5.1 on 2024-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_teamroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='adding_link_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='adding_link_code_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
