# Generated by Django 5.1 on 2024-12-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_team_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRoles',
        ),
    ]
