version: "3.8"

services:
  keycloak-db:
      image: postgres
      environment:
        POSTGRES_DB: ${KK_DB}
        POSTGRES_USER: ${KK_USER}
        POSTGRES_PASSWORD: ${KK_USER_PASSWORD}
      volumes:
        - keycloak_data:/var/lib/postgresql/data
      networks:
        - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: ${KK_DB}
      DB_USER: ${KK_USER}
      DB_PASSWORD: ${KK_USER_PASSWORD}
      KEYCLOAK_ADMIN: ${KK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - my-network
    command:
      - start-dev
  

volumes:
  keycloak_data:

networks:
  my-network:
    driver: bridge